# Fine-tuning Embeddings and Advanced Retrieval

## Overview

- Select an embedding model for fine-tuning

- Adjust the input dataset to the format expected by the S-BERT/Hugging Face: `triplets = {anchor, positives, negatives}`

- Choose a training loss and trains the model with the new datasets

- Use MLFlow to log and register the trained model

- Create an endpoint for the fine-tuned model and deploy it

- Test the deployed endpoint

## Setups

In [0]:
%sql
-- setup to catalog and schema
use catalog `studies`;
use schema `databricks_finetuning`;

In [0]:
import warnings
warnings.filterwarnings('ignore')

from typing import List, Callable
from rich import print
import os
import tempfile

import pandas as pd
import numpy as np

import mlflow
from mlflow.tracking.client import MlflowClient

from datasets import Dataset
import sentence_transformers

import torch

os.environ['TOKENIZERS_PARALLELISM'] = 'false'
torch.set_num_threads(1)
torch.set_num_interop_threads(1)

In [0]:
EXPORT_EVAL_SET_PREDS_FT = True
EVAL_SET_PREDS_FT = 'eval_set_preds_ft'

VS_FT_ENDPOINT_NAME = 'ft_article_vs_endpoint'
VS_FT_INDEX_NAME = 'article_vs_index_ft'
CHUNKS_TABLE_NAME = 'article_chunks'
OUTPUT_TABLE_NAME = 'generated_questions_llm'

REGISTERED_FT_MODEL_NAME = 'ft_embedding_model_endpoint'  # 'ft_embedding_model'
EVAL_SET_PREDS = 'eval_set_preds'

HF_EMBEDDING_MODELS = {
    'gte-small': 'thenlper/gte-small',  # cpu
    'all-MiniLM-L6-v1': 'sentence-transformers/all-MiniLM-L6-v1',  # cpu
    'all-MiniLM-L6-v2': 'sentence-transformers/all-MiniLM-L6-v2',  # cpu
    'bge-small-en-v1.5': 'BAAI/bge-small-en-v1.5',  # cpu
    'bge-large-en': 'BAAI/bge-large-en',  # gpu
}

TRAINING_LOSS = 'MNRL'  
# MNRL (MultipleNegativesRankingLoss), CSL (CosineSimilarityLoss), CMNRL (CachedMultipleNegativesRankingLoss)

infos_env = spark.sql('SELECT current_catalog(), current_schema()').collect()[0]
CATALOG = infos_env[0]
SCHEMA = infos_env[1]
print(f'Catalog: {CATALOG}')
print(f'Schema: {SCHEMA}')


RUN_TRAIN_MODEL = False
RUN_DEPLOY_MODEL = False
CREATE_FT_VS_INDEX = False
RUN_CREATE_EMBED_CHUNKS = True
TEST_FT_MODEL_LATEST_VERSION = False


REDUCE_DATASETS = False
N_MAX = 1000
NUM_TRAIN_EPOCHS = 3
EVAL_STEPS_TRAINING = 1

Catalog: workspace
Schema: default

In [0]:
cuda_is_available = torch.cuda.is_available()
print(cuda_is_available)

False

## Base model for embedding

In [0]:
# https://huggingface.co/models?other=base_model:quantized:thenlper/gte-small
embed_model_name = HF_EMBEDDING_MODELS['gte-small']

embed_model = sentence_transformers.SentenceTransformer(embed_model_name, device='cpu')
# embed_model.to('cpu')

modules.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/583 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/66.7M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: thenlper/gte-small
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [0]:
print('=== Checking the base model ===')
data = ['Helo world!']
embeddings = embed_model.encode(data)
print(f'Input data: {data}')
print(f'Embeddings shape: {embeddings.shape}')
print(embeddings[0][:10])

=== Checking the base model ===

Input data: ['Helo world!']

Embeddings shape: (1, 384)

[-0.01913   0.002438  0.0846   -0.0273    0.007397  0.0232    0.08417
  0.0341   -0.02458  -0.02814 ]

## Prepare the datasets for fine-tuning

In [0]:
train_set = spark.table(f'{CATALOG}.{SCHEMA}.{OUTPUT_TABLE_NAME}_train').toPandas()
eval_set = spark.table(f'{CATALOG}.{SCHEMA}.{OUTPUT_TABLE_NAME}_eval').toPandas()

print(f'train_set.shape: {train_set.shape}')
display(train_set.head())
print(f'\neval_set.shape: {eval_set.shape}')
eval_set.head()

train_set.shape: (58, 4)

path,inputs,id,preds
dbfs:/Volumes/studies/databricks_finetuning/article_infos/pg2_abstract.pdf,We present a model of online content sharing where agents sequentially observe an article and must decide whether to share it with others. This content may or may not contain misinformation. Agents gain utility from positive social media interactions but do not want to be called out for propagating,1,'How do agents' motivations for positive social media interactions influence the spread of misinformation in the proposed model?'
dbfs:/Volumes/studies/databricks_finetuning/article_infos/pg2_abstract.pdf,be called out for propagating misinformation. We characterize the (Bayesian-Nash) equilibria of this social media game and show sharing exhibits strategic complementarity. Our first main result establishes that the impact of homophily on content virality is non-monotone: homophily reduces the broad,2,'How does homophily non-monotonically affect content virality in the Bayesian-Nash equilibrium of the social media sharing game?'
dbfs:/Volumes/studies/databricks_finetuning/article_infos/pg2_abstract.pdf,"nd when there is greater polarization and more divisive content. Finally, we discuss various regulatory solutions to such platform-manufactured misinformation.",5,'What regulatory solutions are proposed to address platform-manufactured misinformation in the context of increased polarization and divisive content?'
dbfs:/Volumes/studies/databricks_finetuning/article_infos/pg2_abstract.pdf,"ximizing engagement tend to design their algorithms to create more homophilic communication patterns (""filter bubbles""). We show that platform incentives to amplify misinformation are particularly pronounced for low-reliability content likely to contain misinformation and when there is greater polar",4,"'Why do platforms incentivize the amplification of low-reliability content, and how does polarization influence this dynamic?'"
dbfs:/Volumes/studies/databricks_finetuning/article_infos/pgs19_20_regulation.pdf,"(c) If $\rho > p^*$ , the provenance policy reduces the virality of misinformation even when the platform optimally chooses the sharing network conditional on the policy.",34,"'What condition ensures that the provenance policy reduces the virality of misinformation, even under optimal platform-driven network selection?'"

eval_set.shape: (25, 4)

                                                path  ...                                              preds
0  dbfs:/Volumes/studies/databricks_finetuning/ar...  ...  'What types of regulations does the paper sugg...
1  dbfs:/Volumes/studies/databricks_finetuning/ar...  ...  'How does the paper model the regulator’s stra...
2  dbfs:/Volumes/studies/databricks_finetuning/ar...  ...  'How do network regulations aim to mitigate th...
3  dbfs:/Volumes/studies/databricks_finetuning/ar...  ...  'How do algorithmic recommendations contribute...
4  dbfs:/Volumes/studies/databricks_finetuning/ar...  ...  'How does misinformation affect agents' abilit...

[5 rows x 4 columns]

**Note:** Training dataset S-BERT = {triplets: triplets = (anchor, positive example, negative example)}

In [0]:
cols_name = {'inputs': 'anchor', 'preds': 'positive'}
# the negative example will be automatic generated by the training loss

if REDUCE_DATASETS:
    train_set_reduced =pd.DataFrame({})
    eval_set_reduced =pd.DataFrame({})

    for path_i in train_set.path.unique():
        row_i = train_set[train_set.path == path_i].sample(1)
        train_set_reduced = pd.concat([train_set_reduced, row_i])
    
    for path_i in eval_set.path.unique():
        row_i = eval_set[eval_set.path == path_i].sample(1)
        eval_set_reduced = pd.concat([eval_set_reduced, row_i])
    
    ft_train_dataset = Dataset.from_pandas(train_set_reduced.rename(columns=cols_name), preserve_index=False)
    ft_eval_dataset = Dataset.from_pandas(eval_set_reduced.rename(columns=cols_name), preserve_index=False)
    
else:
    ft_train_dataset = Dataset.from_pandas(train_set.rename(columns=cols_name), preserve_index=False)
    ft_eval_dataset = Dataset.from_pandas(eval_set.rename(columns=cols_name), preserve_index=False)


ft_train_dataset = ft_train_dataset.select_columns(['anchor', 'positive'])
ft_eval_dataset = ft_eval_dataset.select_columns(['anchor', 'positive'])

print(f'ft_train_dataset.num_rows: {ft_train_dataset.num_rows}')
display(ft_train_dataset.to_pandas())

print(f'ft_eval_dataset.num_rows: {ft_eval_dataset.num_rows}')
ft_eval_dataset.to_pandas()

ft_train_dataset.num_rows: 58

anchor,positive
We present a model of online content sharing where agents sequentially observe an article and must decide whether to share it with others. This content may or may not contain misinformation. Agents gain utility from positive social media interactions but do not want to be called out for propagating,'How do agents' motivations for positive social media interactions influence the spread of misinformation in the proposed model?'
be called out for propagating misinformation. We characterize the (Bayesian-Nash) equilibria of this social media game and show sharing exhibits strategic complementarity. Our first main result establishes that the impact of homophily on content virality is non-monotone: homophily reduces the broad,'How does homophily non-monotonically affect content virality in the Bayesian-Nash equilibrium of the social media sharing game?'
"nd when there is greater polarization and more divisive content. Finally, we discuss various regulatory solutions to such platform-manufactured misinformation.",'What regulatory solutions are proposed to address platform-manufactured misinformation in the context of increased polarization and divisive content?'
"ximizing engagement tend to design their algorithms to create more homophilic communication patterns (""filter bubbles""). We show that platform incentives to amplify misinformation are particularly pronounced for low-reliability content likely to contain misinformation and when there is greater polar","'Why do platforms incentivize the amplification of low-reliability content, and how does polarization influence this dynamic?'"
"(c) If $\rho > p^*$ , the provenance policy reduces the virality of misinformation even when the platform optimally chooses the sharing network conditional on the policy.","'What condition ensures that the provenance policy reduces the virality of misinformation, even under optimal platform-driven network selection?'"
19 See Vanity Fair: https://www.vanityfair.com/news/2020/12/with-the-election-over-facebook-gets-back-to-spreading-misinformation and also https://www.technologyreview.com/2021/03/11/1020600/facebook-responsible-ai-misinformation/. 17,"'How did Facebook resume spreading misinformation after the 2020 election, according to the Vanity Fair and MIT Technology Review articles?'"
"20Formally, the regulator minimizes the virality of content conditional on the article containing misinformation, in mathematical notation, the regulator minimizes $\mathbb{E}_{max}^*|\mathbf{S}_v|\, \nu = M|$.","'What is the formal objective of the regulator in controlling misinformation virality, as expressed mathematically?'"
"21 In practice, certain demographic groups, such as users over 65 years old, appear more likely to accept misinformation without fact-checking, perhaps because of poor media interpretation skills (see Grinberg et al. (2019) and Guess et al. (2019)).","'Which demographic group is more likely to accept misinformation without fact-checking, and what potential reason does the context provide for this behavior?'"
"In Theorem 3, the threshold $r_p$ fully summarizes the extent to which misinformation will spread virally on social media. We next perform comparative statics for this threshold to understand the conditions under which the platform will create a filter bubble and propagate misinformation.",'What does the threshold $r_p$ in Theorem 3 reveal about the conditions under which social media platforms create filter bubbles and propagate misinformation?'
"Proposition 5. There exists $\rho^*<1$ such that: (a) If $\rho > \rho^*$ for any fixed sharing network, the provenance policy reduces the virality of misinformation. (b) If $\rho < \beta^*$ , the provenance policy has an ambiguous effect on the virality of misinformation.","'What is the critical threshold $\rho^*$, and how does it determine the effectiveness of the provenance policy in reducing misinformation virality?'"
"We see that an effective provenance policy, which helps users identify misinformation with high likelihood, successfully reduces the circulation of this content. The reason is that when it is common knowledge that a piece of content contains misinformation, incentives toward sharing are uniformly d",'How does an effective provenance policy reduce the circulation of misinformation?'
now briefly discuss four distinct types of regulations that have been discussed in this context: (1) regulations that force platforms to reveal articles' provenance; (2) censorship or tagging of misinformation; (3) performance targets that require the platform to keep misinformation below a given t,'What are the four distinct types of regulations discussed for addressing misinformation on platforms?'
"our news feed sounds just like you.” Telligly in this context, while Facebook cracked down on misinformation prior to the 2020 election in part due to political pressure, its algorithms have resumed promotion of misinformation in November and December of 2020: ""...the measures [Facebook] could take",'Why did Facebook resume promoting misinformation in November and December 2020 despite prior crackdowns ahead of the 2020 election?'
rmation on the platform.20 We will say the policy has an ambiguous effect when there exists a sharing network (and set of conditions) where the virality of misinformation increases following the regulatory policy.,'What does it mean for a regulatory policy to have an ambiguous effect on misinformation virality?'
"This paper has developed a simple model of the spread of misinformation over social media platforms. A group of Bayesian agents with heterogeneous priors receive and share news items (articles) according to a stochastic sharing network, determined by the social media platform. Articles may be truth",'How do heterogeneous priors and stochastic sharing networks influence the spread of misinformation among Bayesian agents on social media platforms?'
"Though simple and parsimonious, the model encapsulates several rich strategic interactions. Agents receive utility from sharing truthful articles and not misinformation, but also enjoy peer engagement with shared content. The former force pushes agents toward sharing pro-attitudinal content, wherea",'How do agents balance the utility of sharing truthful content against the desire for peer engagement in the model?'
"We also study regulations aimed at minimizing the spread of misinformation. Revealing the provenance of a news item (for example, providing full context for a quote) can be useful, because this additional information allows users to more easily fact-check the content for veracity. However, we also",'How does revealing the provenance of a news item help in combating misinformation?'
"We provide several comparative static results. Some of those are very intuitive, though still useful for interpreting a range of results in the emerging empirical literature on social media and misinformation. For example, we find that while misinformation typically spreads less than truthful conte",'What is one intuitive comparative static result presented in the paper regarding the spread of misinformation versus truthful content on social media?'
"can suffer from spreading misinformation, even those who agree with their message would not share them widely. In contrast, high homophily creates echo chambers, where users share low-reliability messages aligned with their beliefs, because they understand that there are few negative reputational c",'How does high homophily contribute to the spread of low-reliability misinformation within online communities?'
"l out another agent for propagating misinformation (""dislike""). Misinformation spreads when agents share articles expecting positive social media feedback and little negative reactions.",'What conditions enable misinformation to spread according to the agent-based model described?'
"r setting, it brought out certain new strategic forces—highlighting how social media actions exhibit strategic complementarity and how the degree of homophily alters agents' strategic behavior. Nevertheless, misinformation may be particularly damaging when agents have cognitive limitations and are o",'How do cognitive limitations and homophily interact to influence the strategic behavior of agents in the spread of misinformation on social media?'
"reads less than truthful content (holding all else constant), more sensational content tends to be shared more. Moreover, when misinformation is correlated with sensationalism, the rapid spread misinformation can be problematic.",'Why does sensational content contribute to the rapid spread of misinformation?'
"25 Budak, Ceren, Divyakant Agrawal, and Amr El Abbadi (2011), “Limiting the spread of misinformation in social networks.” In Proceedings of the 20th international conference on World wide web, WW 11, 665–674.","'How do Budak, Agrawal, and El Abbadi propose to limit the spread of misinformation in social networks?'"
"Guess, Andrew, Brendan Nyhan, and Jason Reifler (2018), “Selective exposure to misinformation: Evidence from the consumption of fake news during the 2016 US presidential campaign.” European Research Council, 9, 4.","'What evidence did Guess, Nyhan, and Reifler find regarding selective exposure to fake news during the 2016 U.S. presidential campaign?'"
"Mostagir, Mohamed, Asu Ozdaglar, and James Siderius (2021), ""When is society susceptible to manipulation?"" Management Science, forthcoming. Mostagir, Mohamed and James Siderius (2021), “Social inequality and the spread of misinformation."" Management Science, forthcoming.",'How does social inequality contribute to the spread of misinformation according to Mostagir and Siderius (2021)?'
"Pennycook, Gordon and David G. Rand (2019a), “Fighting misinformation on social media using crowdsourced judgments of news source quality,” Proceedings of the National Academy of Sciences, 116, 2521–2526.",'How does the study propose to combat misinformation on social media using crowdsourced judgments of news source quality?'
"Pennycook, Gordon, Ziv Epstein, Mohsen Mosleh, Antonio A. Arechar, Dean Eckles, and David G. Rand (2021). “Shifting attention to accuracy can reduce misinformation online.” Nature, 592, 590–595. Pennycook, Gordon, Jonathon McPhetres, Yunhao Zhang, Jackson G. Lu, and David G. Rand (2020b),",'Shifting attention to accuracy can reduce misinformation online?'
"Topkis, Donald M. (1998). Supermodularity and Complementarity, first edition edition. Törnberg, Petter (2018), “Echo chambers and viral misinformation: Modeling fake news as complex contagion.” PLOS ONE, 13.","'How does Törnberg (2018) model the spread of fake news as a complex contagion within echo chambers, and how does this relate to the concept of complementarity discussed in Topkis (1998)?'"
"Vicario, Michela Del, Alessandro Bessi, Fabiana Zollo, Fabio Petroni, Antonio Scala, Guido Caldarelli, H. Eugene Stanley, and Walter Quattrociocchi (2016), ""The spreading of misinformation online."" Proceedings of the National Academy of Sciences, 113, 554–559.",'How does homophily contribute to the spread of misinformation on online platforms according to Vicario et al. (2016)?'
"-minded individuals, agents become more likely to share questionable content. Strategic complementarities amplify this effect, because when others are expected to share, the benefits from sharing and reduces the likelihood of being called out for spreading misinformation are greater. It is particula",'How do strategic complementarities influence the sharing of questionable content by like-minded individuals?'
"7 Papanastasiou (2020) also discusses platform incentives, but assumes that the platform is interested in limiting misinformation. Our reading of the evidence in this instance, too, favors our interpretation, where platforms such as Facebook are (or at the very least used to be before regulatory pr","'What does Papanastasiou (2020) assume about platform incentives regarding misinformation, and how does the author contrast this with their own interpretation of platforms like Facebook?'"
"If platform algorithms are propagating misinformation, can public policy counter and discourage this type of behavior?4 The answer is yes, but with some caveats. In the last part of the paper, we discuss four different types of regulatory policies, and in each case, we show how they may reduce misi",'What are the four types of regulatory policies discussed in the paper that could counter misinformation propagated by platform algorithms?'
"In this paper, we develop a parsimonious model of online sharing behavior in the presence of misinformation, and as a first step, we focus on the behavior of fully Bayesian agents.3 Our model is inhabited by a set of N agents, each of which has a prior about the state of the world (""ideological bia",'How does the paper model the sharing behavior of fully Bayesian agents in the presence of misinformation?'
"Much previous work has focused on the susceptibility of boundedly-rational agents to engage with misinformation. In Acemoglu et al. (2010) and Acemoglu et al. (2013), the existence of persuasive agents can impede information aggregation and enable misinformed beliefs to survive, and sometimes even",'How do persuasive agents affect information aggregation and the persistence of misinformed beliefs according to Acemoglu et al. (2010) and Acemoglu et al. (2013)?'
"Related Literature. Our paper builds on a large body of work on models of misinformation. In addition to the literature mentioned previously, several other papers in this literature are related to our findings.","'What existing literature on misinformation models does the paper build upon, and how do those works relate to its findings?'"
"backfire when it instills a sense of ""false security"" that the content has been verified by previous social media users. Second, we look at potential censorship of articles identified by a regulator as likely containing misinformation. While censorship can help reduce the viral spread of misinforma","'How can fact-checking interventions backfire by creating a sense of ""false security"" among social media users?'"
"containing misinformation), a message (right-wing or left-wing), and a level of reliability (which determines the likelihood of misinformation), is then seeded at one of the agents. The message and the level of reliability of the article are common knowledge, while whether it is truthful or contain",'What information is considered common knowledge when a message is seeded among agents in the model?'
"egic decisions — have been studied in Budak et al. (2011), Nguyen et al. (2012), and Törnberg (2018). Our contribution relative to this literature is the possibility that misinformation spreads because of the strategic interactions of Bayesian agents and is exacerbated by profit-maximizing platform",'How does the paper explain the spread of misinformation in terms of strategic interactions among Bayesian agents and profit-maximizing platforms?'
eliability and likely to contain misinformation.,'Why is the content described as unreliable and likely to contain misinformation?'
"eported receiving at least some of their news from social media (Levy (2021)). At the same time, there is growing concern about viral misinformation in social media, including made-up news stories such as those claiming that there were no mass shootings under Donald Trump or that Hillary Clinton app","'What is the concern raised about the role of social media in the spread of misinformation, as illustrated by examples like false claims about mass shootings and Hillary Clinton?'"
"its message and believe it to contain misinformation. Engagement with low-reliability content can be increased if the platform ensures that it remains among users ideologically aligned with its message, who would be willing to share it with like-minded others without fear of being called out by user",'How do ideologically aligned communities on platforms contribute to the spread of low-reliability content by reducing fear of social backlash?'
"ke-minded users (Sunstein (2018), Lazer et al. (2018)). Törnberg (2018) and Vicario et al. (2016) show that echo chambers reinforce existing political viewpoints and tend to propagate misinformation. Social media, much more than traditional media, allows individual users to choose who and what they",'How do echo chambers on social media contribute to the spread of misinformation according to Törnberg (2018) and Vicario et al. (2016)?'
"material that was unlikely to become viral in any case, and the least reliable content may still continue to circulate virally. Lastly, we show how direct regulation of platform algorithms can reduce misinformation, but also point out that the non-monotone effects of homophily imply that such regula",'How does homophily affect the impact of direct algorithmic regulation on misinformation dissemination?'
"media as well (Guess et al. (2018)). Despite the importance and salience of these issues, we do not currently have a framework to understand how online interactions impact the spread of misinformation and what factors shape incentives for sharing low-reliability content.",'What framework is currently lacking to understand how online interactions influence the spread of misinformation and the incentives for sharing low-reliability content?'
mp or that Hillary Clinton approved ISIS weapon sales. Some recent evidence also suggests that misinformation on social media has impacted critical decisions such as vaccinations against COVID-19 (see Pennycook et al. (2018); Pennycook et al. (2020b)).,"'How has misinformation on social media been shown to influence public behavior, particularly in relation to COVID-19 vaccinations?'"
"njectured to have fueled misinformation is the general political polarization in many countries, and especially the United States; and there is some preliminary evidence suggesting that polarization has contributed to selective exposure to questionable content on social media as well (Guess et al. (",'What role does political polarization play in the spread of misinformation on social media according to the context?'
sed to be before regulatory pressure mounted) fairly indifferent to the presence of misinformation but strongly prioritize engagement maximization.,"'How did platforms behave toward misinformation prior to regulatory pressure, and what was their primary objective?'"
"show how they may reduce misinformation but also point out the possibility that, if they are not designed well, they can backfire and exacerbate the problem.",'How can interventions to reduce misinformation backfire if not designed well?'
"ther it is truthful or contains misinformation is unobserved, and agents form beliefs about this",'How do agents form beliefs about the truthfulness of information when its veracity is unobserved?'
"(ii) Payoffs from dislike, $D$ depend on whether the article contains misinformation. We assume, in particular, that disliking has a cost of $\hat{c}>0$ , regardless of whether the article is truthful (because of, say, the effort required to actively call out misinformation). In addition, disliking","'How does the cost of disliking, $\hat{c}$, influence user behavior toward truthful versus misleading articles in the model?'"
(ii) The veracity of the article is $\nu=\mathcal{T}$ (contains truthful content) with probability $\phi(r)$ or is $\nu=\mathcal{M}$ (contains misinformation) with probability $1-\phi(r)$ . We assume that $\phi$ is increasing,"'How does the probability function $\phi(r)$ influence the likelihood of an article being truthful versus misleading, and what does its increasing nature imply about the relationship between $r$ and information veracity?'"

ft_eval_dataset.num_rows: 25

                                               anchor                                           positive
0   6 Regulation\nOur analysis so far raises the n...  'What types of regulations does the paper sugg...
1   We consider the effects of these policies both...  'How does the paper model the regulator’s stra...
2   misinformation below a given threshold; (4) ne...  'How do network regulations aim to mitigate th...
3   and recommends articles to users with aligned ...  'How do algorithmic recommendations contribute...
4   f misinformation, agents will be uncertain abo...  'How does misinformation affect agents' abilit...
5   information. We can also use this extended set...  'How does the probability of misinformation af...
6   ity of content. Because this article is unlike...  'How does increased homophily affect the sprea...
7   latform. Articles may be truthful and informat...  'How do agents decide whether to share, ignore...
8   rk. Fully endogenizing reputational concerns, ...  'How might fully endogenizing reputational con...
9   Nguyen, Nam P., Guanhua Yan, My T. Thai, and S...  'What strategies does the paper propose for co...
10  6 As already noted, echo chambers appear centr...  'Which studies are cited to support the role o...
11  a strategic principal who wants to persuade ag...  'How can a strategic principal exploit social ...
12  a striking result: when the relevant articles ...  'Why do social media platforms that maximize e...
13  e reputation loss from being called out for sh...  'How does the prospect of reputation loss infl...
14  gically similar to them). Low levels of homoph...  'How does low homophily contribute to the down...
15  n are greater. It is particularly telling that...  'Why does homophily contribute to the viral sp...
16  of the algorithmic choices of the platform tha...  'How do platform algorithms that prioritize en...
17  of the world ("ideological bias"), and is conn...  'How does the network structure shaped by soci...
18  the amount of misinformation that circulates o...  'Why might platforms meet regulatory performan...
19  the viral spread of misinformation, it also ge...  'How does the "implied truth" effect contribut...
20  (iii) Following a decision to share, $S$ , an ...  'How does the model account for the trade-off ...
21  5\n(iii) If $\nu=\mathcal{T}$ (the article is ...  'How does the probability $p > 1/2$ influence ...
22  7\nfor example, evidence from Facebook in Alta...  'What evidence is provided to support the clai...
23  probability 1, and is always preferred to igno...  'Why is sharing an article with probability 1 ...
24  r a left-wing or right-wing idea. Finally, $\n...  'What does the variable $\nu$ represent in the...

## Define training loss

In [0]:
if TRAINING_LOSS == 'MNRL':
    train_loss = sentence_transformers.losses.MultipleNegativesRankingLoss(model=embed_model)
elif TRAINING_LOSS == 'CSL':
    train_loss = sentence_transformers.losses.CosineSimilarityLoss(model=embed_model)
elif TRAINING_LOSS == 'CMNRL':
    train_loss = sentence_transformers.losses.CachedMultipleNegativesRankingLoss(
        model=embed_model,
        mini_batch_size=pow(2, 1)
    )
else:
    raise ValueError(f'Unsupported training loss: {TRAINING_LOSS}')
    
print(train_loss)

MultipleNegativesRankingLoss(
  (model): SentenceTransformer(
    (0): Transformer({'max_seq_length': 512, 'do_lower_case': False, 'architecture': 'BertModel'})
    (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens':
True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False,
'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
    (2): Normalize()
  )
  (cross_entropy_loss): CrossEntropyLoss()
)

## Perform fine-tuning

In [0]:
# remove distributed vars to avoid cluster issues
for var in ['RANK', 'WORLD_SIZE', 'LOCAL_RANK', 'MASTER_ADDR', 'MASTER_PORT']:
    os.environ.pop(var, None)

In [0]:
if RUN_TRAIN_MODEL:
    # https://huggingface.co/blog/train-sentence-transformers

    # tranining parameters
    tmp_dir = tempfile.TemporaryDirectory()
    base_model = sentence_transformers.SentenceTransformer(embed_model_name, device='cpu')

    args = sentence_transformers.training_args.SentenceTransformerTrainingArguments(
        auto_find_batch_size=False,
        data_seed=42,
        eval_steps=EVAL_STEPS_TRAINING,
        learning_rate=2e-5,
        num_train_epochs=NUM_TRAIN_EPOCHS,
        output_dir=tmp_dir.name,
        seed=42,
        use_cache=False,
        use_cpu=True,
        warmup_steps=0,
    )

### Run training

In [0]:
if RUN_TRAIN_MODEL:

    class SentenceTransformerWrapper(mlflow.pyfunc.PythonModel):
        '''Wrapper for log the model in mlflow.'''

        def load_context(self, context):
            model_path = context.artifacts['model_path']
            self.model = sentence_transformers.SentenceTransformer(model_path)

        def predict(
            self,
            context: mlflow.pyfunc.PythonModelContext,
            model_input: List[str]
        ) -> List[List[float]]:
            embeddings = self.model.encode(model_input)
            return np.nan_to_num(embeddings, nan=0.0).tolist()

    try:
        trainer = sentence_transformers.SentenceTransformerTrainer(
            model=base_model,
            args=args,
            train_dataset=ft_train_dataset,
            eval_dataset=ft_eval_dataset,
            loss=train_loss,
        )

        print('Training the model ...')
        with mlflow.start_run() as run:

            trainer.train()

            local_model_path = 'fine_tuned_model'
            trainer.model.save(local_model_path)

            full_model_name = f'{CATALOG}.{SCHEMA}.{REGISTERED_FT_MODEL_NAME}'

            model_info = mlflow.pyfunc.log_model(
                name='model',
                python_model=SentenceTransformerWrapper(),
                artifacts={'model_path': local_model_path},
                registered_model_name=full_model_name,
                input_example=['Hello World!'],
            )

            model_uri = model_info.model_uri
        print('Done.')
        
        print(f'\nModel URI: {model_uri}')
        print(f'Unity Catalog model name: {full_model_name}')
        print(f'Local path: {local_model_path}')

    except Exception as e:
        print(f"Error:\n{e}")

## Inference with the fine-tuned model

In [0]:
def get_latest_model_version(model_name: str) -> int:
    mlflow_client = MlflowClient()
    model_version_infos = mlflow_client.search_model_versions(f"name = '{model_name}'")
    return max([int(i.version) for i in model_version_infos])

In [0]:
if TEST_FT_MODEL_LATEST_VERSION:
    latest_version = get_latest_model_version(model_name=f'{CATALOG}.{SCHEMA}.{REGISTERED_FT_MODEL_NAME}')
    print(f'Latest model version: {latest_version}')

In [0]:
if TEST_FT_MODEL_LATEST_VERSION:
    # deployed_version = 15
    latest_model_uc = f'models:/{CATALOG}.{SCHEMA}.{REGISTERED_FT_MODEL_NAME}/{latest_version}'
    try:
        pyfunc_model = mlflow.pyfunc.load_model(latest_model_uc)
    except Exception as e:
        print(f"Failed to load model at {latest_model_uc}: {e}")

    input_example = pyfunc_model.input_example

    loaded_model = mlflow.pyfunc.load_model(
        latest_model_uc
    )

    print(f'Input example:\n{input_example}\n')

    print('=== Base model ===')
    embeddings_base = embed_model.encode(input_example)
    print(f'Embeddings shape: {embeddings_base.shape}')
    print(list(embeddings_base[0][:10]))

    print('=== FT model ===')
    embeddings_ft = loaded_model.predict(input_example)
    print(f'Embeddings shape: {len(embeddings_ft)}')
    print(embeddings_ft[0][:10])

In [0]:
raise ValueError(f'Check whether the fine-tuned embedding model has already been deployed.')

## Load dataset for evaluation

In [0]:
prev_eval_set_df = spark.read.table(f'{CATALOG}.{SCHEMA}.{EVAL_SET_PREDS}')
display(prev_eval_set_df.show(5))

In [0]:
(
    prev_eval_set_df
    .groupBy('path')
    .count()
    .orderBy(desc('count'))
    .show(truncate=False)
)

## Deploy the fine-tuned model

- Estimated waiting time: ~50 min

- To deploy an endpoint for the fine-tuned model, use the UI or the commented code below.

In [0]:
# import secrets

# secret_key = secrets.token_hex(16)
# print(secret_key)

In [0]:
# # Setup secrets

# databricks secrets list-scopes
# databricks secrets create-scope genai_deploy
# databricks secrets put-secret genai_deploy GENAI_API_KEY

# ---

# databricks secrets put-secret --json '{ "scope": "finetuning_deploy", "key": "deploy_host", "string_value": "<host-name>"}
# databricks secrets put-secret --json '{ "scope": "finetuning_deploy", "key": "deploy_token", "string_value": "<token-value>"}

In [0]:
# from databricks.sdk.service.serving import EndpointCoreConfigInput 

# endpoint_config_dict = {
# 	'served_models': [{
# 		'model_name': REGISTERED_FT_MODEL_NAME,
# 		'model_version': latest_version,
# 		'scale_to_zero_enabled': True,
# 		'workload_size': 'Small',
# 		'enviroment_vars': {
# 			'DATABRICKS_TOKEN': '{{secrets/latest_model/deploy_host}}',
# 			'DATABRICKS_HOST': '{{secrets/latest_model/deploy_host}}'
# 		}
# 	}],
# 	'auto_capture_config': {
# 		'catalog_name': CATALOG,
# 		'schema_name': SCHEMA,
# 		'table_name_prefix': 'ft_embedding_model_gte_small'
# 	}
# }

# endpoint_config = EndpointCoreConfigInput.from_dict(endpoint_config_dict)
# print(endpoint_config)

In [0]:
# workspace_client = WorkspaceClient()
# print([endpoint for endpoint in workspace_client.list()])

# endpoint_name = REGISTERED_FT_MODEL_NAME
# db_host = DATABRICKS_HOST

# endpoint_url = f'{db_host}/ml/endpoints/{endpoint_name}'

# workspace_client.serving_endpoints.update_config_and_wait(name=endpoint_name, served_models=edpoint_config.served_models)

<img src='./imgs/serving_endpoint_ft_embedding.png'>

## Test the deployed endpoint for the fine-tuned model

In [0]:
%sql
SELECT ai_query(
  'ft_embedding_model_endpoint',
  'Hello World!'
)